services:
    app:
        build: .
        restart: always
        environment:
            - NUXT_PUBLIC_SUPABASE_URL=https://supabase-alphabet.samlas.ru
            - NUXT_PUBLIC_SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzQ5NzYyMDAwLCJleHAiOjE5MDc1Mjg0MDB9.Xgyumqm-pCBHqTlJz_SanyPprEi6szLxGkOPRC3Owk8
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        restart: always
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        ports:
            - 8886:80
