create table "public"."demo" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "results" json,
    "lesson_id" bigint not null
);


alter table "public"."demo" enable row level security;

CREATE UNIQUE INDEX demo_pkey ON public.demo USING btree (id);

alter table "public"."demo" add constraint "demo_pkey" PRIMARY KEY using index "demo_pkey";

grant delete on table "public"."demo" to "anon";

grant insert on table "public"."demo" to "anon";

grant references on table "public"."demo" to "anon";

grant select on table "public"."demo" to "anon";

grant trigger on table "public"."demo" to "anon";

grant truncate on table "public"."demo" to "anon";

grant update on table "public"."demo" to "anon";

grant delete on table "public"."demo" to "authenticated";

grant insert on table "public"."demo" to "authenticated";

grant references on table "public"."demo" to "authenticated";

grant select on table "public"."demo" to "authenticated";

grant trigger on table "public"."demo" to "authenticated";

grant truncate on table "public"."demo" to "authenticated";

grant update on table "public"."demo" to "authenticated";

grant delete on table "public"."demo" to "service_role";

grant insert on table "public"."demo" to "service_role";

grant references on table "public"."demo" to "service_role";

grant select on table "public"."demo" to "service_role";

grant trigger on table "public"."demo" to "service_role";

grant truncate on table "public"."demo" to "service_role";

grant update on table "public"."demo" to "service_role";

create policy "Enable insert for authenticated users only"
on "public"."demo"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable users to update their own data only"
on "public"."demo"
as permissive
for update
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable users to view their own data only"
on "public"."demo"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));




